### ISSUE TITLE
TEST無視ケースの間違い

### ISSUE THREAD

**Issue by poteto0** [poteto0/poteto#145]
```yaml
- name: Test
   run: go test ./... -coverprofile cover.out.tmp -bench . -benchtime 100000x
- name: remove not test path
   run: cat cover.out.tmp | grep -v "github.com/poteto0/poteto/cmd/template" > cover2.out.tmp
- name: remove not test path2
   run: cat cover2.out.tmp | grep -v "github.com/poteto0/poteto/cmd/template" > coverage.txt
```

`github.com/poteto0/poteto/cmd/template` -> `github.com/poteto0/poteto/constant`
